# Use DecapBridge PKCE auth (required)
backend:
  name: git-gateway
  repo: Callowhill-Web-Designs/PA-Lead-Inspectors
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/db9f1d7d-a4c6-4942-81b4-424254d046f7/pkce
  auth_token_endpoint: /sites/db9f1d7d-a4c6-4942-81b4-424254d046f7/token
  gateway_url: https://gateway.decapbridge.com

  # See who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Enable PKCE fields (optional, recommended)
auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in Decap CMS (optional)
site_url: https://paleadinspect.com

# Where should uploaded files be saved
media_folder: src/assets/images/blog

# Where should media be served, relative to the base of the built site
public_folder: /assets/images/blog

collections:
    # SETTINGS CONFIG
    - label: Settings
      name: settings
      delete: false
      editor:
          preview: false
      files:
          - label: Website Settings
            name: website_settings
            file: src/_data/client.json
            description: Allows a client to update their own contact information, through the default client.json file
            fields:
                - label: Business Name
                  name: name
                  widget: string
                  summary: Used in browser tab and sharing links

                - label: Email
                  name: email
                  widget: string
                  summary: Main email for customers to contact you

                - label: Unformatted Telephone
                  name: phoneForTel
                  widget: string
                  summary: Used for clickable links to phone. Enter in format xxx-xxx-xxxx

                - label: Formatted Telephone
                  name: phoneFormatted
                  widget: string
                  summary: Used for display on website. Enter in your preferred format

                - label: Address
                  name: address
                  widget: object
                  collapsed: true
                  fields:
                      - label: Address Line One
                        name: lineOne
                        widget: string

                      - label: Address Line Two
                        name: lineTwo
                        widget: string

                      - label: City
                        name: city
                        widget: string

                      - label: State
                        name: state
                        widget: string

                      - label: Zip Code
                        name: zip
                        widget: string

                      - label: Google Maps Link
                        name: mapLink
                        widget: string
                        summary: Provide a Google Maps share link to guide visitors to your physical locations

                - label: Social Media
                  name: social
                  widget: object
                  collapsed: true
                  fields:
                      - label: Facebook
                        name: facebook
                        widget: string

                      - label: Twitter
                        name: twitter
                        widget: string

                      - label: Instagram
                        name: instagram
                        widget: string

                      - label: Youtube
                        name: youtube
                        widget: string

    # BLOG CONFIG
    - label: Blog
      name: blog
      folder: src/content/blog
      create: true
      slug: "{{slug}}"
      fields:
          - label: Title
            name: title
            widget: string

          - label: Description
            name: description
            widget: string

          - label: Author
            name: author
            widget: string

          - label: Date
            name: date
            widget: datetime

          - label: Tags
            name: tags
            widget: list
            default:
                - post

          - label: Featured Image
            name: image
            widget: image

          - label: Image Caption
            name: imageAlt
            widget: string

          - label: Body
            name: body
            widget: markdown